---
title: Luciacardenas.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 5
language: en-uk
name: Lucia´s blog
description: this is a blog were lucia is writting some beautiful content.
author: Lucia Cardenas
nickname: luciacardenas
bio: A paranormal expert and his daughter bunk in an abandoned house populated by mischievous ghosts and one friendly one.
location: Paris, France
url: http://luciacardenas.github.io
image: /assets/images/casper.png
google_analytics: UA-69281367-1
disqus: username

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ""

# Permalinks
# permalink: /:title
defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - "*.Rmd"
