# Site settings

title: Lucia Cardenas Melgarejo
description: > # this means to ignore newlines until "baseurl:"
     Growth Marketer and Innovation Consultant
url: "https://luciacardenas.me" # the base hostname & protocol for your site, e.g. http://example.com

# Needed by jekyll-seo-tag
twitter: 
  username: Cardenas_Lu
logo: '/assets/img/lucia-lion.jpg' 
linkedin_username:  luciacardenasmelgarejo
github_username:  luciacardenas

google_analytics: UA-147263429-1
google_site_verification: 

# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
 
collections_dir: collections
collections:
  fr:
    output: true
  es:
    output: true
  en:
    output: true

defaults:
  - {scope: {path: "", layout: default, type: "en"}, values: {lang: 'en_US', image: '/assets/img/lucia-lion.jpg', description: 'Growth Marketer and Innovation Consultant', title: 'Lucia Cardenas Melgarejo' }}
  - {scope: {path: "", layout: default, type: "fr"}, values: {lang: 'fr_FR', image: '/assets/img/lucia-lion.jpg', description: 'Growth Marketer et Consultante en innovation', title: 'Lucia Cardenas Melgarejo' }}
  - {scope: {path: "", layout: default, type: "es"}, values: {lang: 'es_ES', image: '/assets/img/lucia-lion.jpg', description: 'Growth Marketer & Consultora de innovación', title: 'Lucia Cardenas Melgarejo' }}
  - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title', animation: true}}
