# Site settings

title: Lucia Cardenas Melgarejo
description: > # this means to ignore newlines until "baseurl:"
     Growth Marketer and Innovation Consultant
url: "https://luciacardenas.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Needed by jekyll-seo-tag
twitter: 
  username: Cardenas_Lu
logo: '/assets/img/lucia-lion.jpg' 
linkedin_username:  luciacardenasmelgarejo
github_username:  luciacardenas

google_analytics: 
google_site_verification: 

# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
 
include:
  - _pages

defaults:
    - {scope: {path: "", layout: default, type: "pages"}, values: {image: '/assets/img/lucia-lion.jpg'}}

